// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {CalibrationRegistry} from "../src/CalibrationRegistry.sol";
import {AgentIdentity} from "../src/AgentIdentity.sol";

contract AgentIdentityTest {
    CalibrationRegistry public reg;
    AgentIdentity public identity;

    uint256 constant WAD = 1e18;

    function setUp() public {
        reg = new CalibrationRegistry();
        identity = new AgentIdentity(address(reg));

        // Seed an agent in the registry
        reg.seedBrier(address(0x1), 0.10e18, 220);
    }

    // --- Mint ---

    function test_mint_basic() public {
        uint256 tokenId = identity.mint(address(0x1), "agent-oracle", "");

        require(tokenId == 1, "first token should be ID 1");
        require(identity.totalSupply() == 1, "supply should be 1");
        require(identity.balanceOf(address(0x1)) == 1, "balance should be 1");
        require(identity.ownerOf(1) == address(0x1), "owner should be agent");
    }

    function test_mint_withMetadata() public {
        identity.mint(address(0x1), "agent-oracle", "ipfs://Qm123abc");

        string memory uri = identity.tokenURI(1);
        // Should return the custom URI
        require(
            keccak256(bytes(uri)) == keccak256(bytes("ipfs://Qm123abc")),
            "should return custom URI"
        );
    }

    function test_mint_autoGeneratedURI() public {
        identity.mint(address(0x1), "agent-oracle", "");

        string memory uri = identity.tokenURI(1);
        // Should be non-empty JSON
        require(bytes(uri).length > 0, "auto-generated URI should not be empty");
    }

    function test_mint_revert_duplicate() public {
        identity.mint(address(0x1), "agent-oracle", "");

        try identity.mint(address(0x1), "agent-oracle-2", "") {
            revert("should revert on duplicate mint");
        } catch {}
    }

    function test_mint_revert_zeroAddress() public {
        try identity.mint(address(0), "nobody", "") {
            revert("should revert on zero address");
        } catch {}
    }

    // --- Batch mint ---

    function test_mintBatch() public {
        address[] memory agents = new address[](3);
        agents[0] = address(0x1);
        agents[1] = address(0x2);
        agents[2] = address(0x3);

        string[] memory labels = new string[](3);
        labels[0] = "agent-oracle";
        labels[1] = "agent-reliable";
        labels[2] = "agent-novice";

        string[] memory uris = new string[](3);
        uris[0] = "";
        uris[1] = "";
        uris[2] = "";

        uint256[] memory tokenIds = identity.mintBatch(agents, labels, uris);

        require(tokenIds.length == 3, "should return 3 token IDs");
        require(tokenIds[0] == 1, "first ID should be 1");
        require(tokenIds[1] == 2, "second ID should be 2");
        require(tokenIds[2] == 3, "third ID should be 3");
        require(identity.totalSupply() == 3, "supply should be 3");
    }

    // --- Agent profile ---

    function test_getAgentProfile_withToken() public {
        identity.mint(address(0x1), "agent-oracle", "");

        (
            uint256 tokenId,
            string memory label,
            uint256 mintedAt,
            uint256 brierScore,
            uint256 numPredictions,
            uint256 calibrationWeight,
            bool hasToken,
            bool registeredInCalibration
        ) = identity.getAgentProfile(address(0x1));

        require(tokenId == 1, "tokenId should be 1");
        require(keccak256(bytes(label)) == keccak256(bytes("agent-oracle")), "label mismatch");
        require(mintedAt > 0, "mintedAt should be set");
        require(brierScore == 0.10e18, "brier should match registry");
        require(numPredictions == 220, "predictions should match registry");
        require(calibrationWeight > WAD, "weight should be > BASE_WEIGHT");
        require(hasToken, "should have token");
        require(registeredInCalibration, "should be registered");
    }

    function test_getAgentProfile_noToken() public view {
        (
            , , , , , ,
            bool hasToken,
            bool registeredInCalibration
        ) = identity.getAgentProfile(address(0x99));

        require(!hasToken, "should not have token");
        require(!registeredInCalibration, "should not be registered");
    }

    // --- Soulbound restrictions ---

    function test_transferFrom_blocked() public {
        identity.mint(address(0x1), "agent-oracle", "");

        try identity.transferFrom(address(0x1), address(0x2), 1) {
            revert("transferFrom should be blocked");
        } catch {}
    }

    function test_approve_blocked() public {
        identity.mint(address(0x1), "agent-oracle", "");

        try identity.approve(address(0x2), 1) {
            revert("approve should be blocked");
        } catch {}
    }

    function test_setApprovalForAll_blocked() public view {
        try identity.setApprovalForAll(address(0x2), true) {
            revert("setApprovalForAll should be blocked");
        } catch {}
    }

    function test_getApproved_returnsZero() public {
        identity.mint(address(0x1), "agent-oracle", "");
        require(identity.getApproved(1) == address(0), "getApproved should return zero");
    }

    function test_isApprovedForAll_returnsFalse() public view {
        require(!identity.isApprovedForAll(address(0x1), address(0x2)), "should be false");
    }

    // --- ERC-165 ---

    function test_supportsInterface_erc721() public view {
        require(identity.supportsInterface(0x80ac58cd), "should support ERC-721");
    }

    function test_supportsInterface_erc165() public view {
        require(identity.supportsInterface(0x01ffc9a7), "should support ERC-165");
    }

    // --- Metadata update ---

    function test_updateMetadata() public {
        identity.mint(address(0x1), "agent-oracle", "");
        identity.updateMetadata(1, "ipfs://QmUpdated");

        string memory uri = identity.tokenURI(1);
        require(
            keccak256(bytes(uri)) == keccak256(bytes("ipfs://QmUpdated")),
            "URI should be updated"
        );
    }

    function test_updateMetadata_revert_nonexistent() public {
        try identity.updateMetadata(999, "ipfs://QmFake") {
            revert("should revert on nonexistent token");
        } catch {}
    }

    // --- Token lookup ---

    function test_agentToToken_mapping() public {
        identity.mint(address(0x1), "agent-oracle", "");
        identity.mint(address(0x2), "agent-reliable", "");

        require(identity.agentToToken(address(0x1)) == 1, "agent 1 should have token 1");
        require(identity.agentToToken(address(0x2)) == 2, "agent 2 should have token 2");
    }

    function test_ownerOf_revert_nonexistent() public view {
        try identity.ownerOf(999) {
            revert("should revert on nonexistent token");
        } catch {}
    }

    function test_tokenURI_revert_nonexistent() public view {
        try identity.tokenURI(999) {
            revert("should revert on nonexistent token");
        } catch {}
    }
}
